package com.promptstudio.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents an AI Chat conversation session belonging to a user.
 * Maps to the "chat_sessions" collection in MongoDB. Messages are
 * embedded directly as a list within the session document rather than
 * stored in a separate collection, since chat messages are always
 * accessed and displayed together with their parent session and have
 * no independent lifecycle of their own — a natural fit for MongoDB's
 * document model.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "chat_sessions")
public class ChatSession {

    /** Unique MongoDB-generated identifier for this chat session. */
    @Id
    private String id;

    /** ID of the User who owns this chat session. */
    @Indexed
    @Field("user_id")
    private String userId;

    /** Display title for this session (auto-generated from first message, or user-renamed). */
    @Field("title")
    @Builder.Default
    private String title = "New Chat";

    /** The ordered list of messages exchanged in this session. */
    @Field("messages")
    @Builder.Default
    private List<ChatMessage> messages = new ArrayList<>();

    /** Timestamp when this session was created (auto-populated). */
    @CreatedDate
    @Field("created_at")
    private LocalDateTime createdAt;

    /** Timestamp when this session was last updated (auto-populated). */
    @LastModifiedDate
    @Field("updated_at")
    private LocalDateTime updatedAt;

    /**
     * Represents a single message within a chat session — either sent
     * by the user or generated by the AI assistant. Embedded as a
     * nested static class rather than a separate top-level entity.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ChatMessage {

        /** Who sent this message: "USER" or "ASSISTANT". */
        private String role;

        /** The text content of the message. */
        private String content;

        /** Timestamp when this individual message was sent. */
        private LocalDateTime timestamp;
    }
}